name: deploy
on:
  push:
    branches:    
      - master
jobs:
  deploy_job:
    name: deploy job
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: start deploy
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: |
        sh ./deploy.sh